name = "SequenceLogos"
uuid = "7a3f67ce-6eeb-4904-9da4-2cbd106a5944"
authors = "Jorge Fernandez-de-Cossio-Diaz <j.cossio.diaz@gmail.com>"
version = "0.2.2"

[deps]
LazyArtifacts = "4af54fe1-eca0-43a8-85a7-787d91b784e3"
Makie = "ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a"

[compat]
LazyArtifacts = "1.10"
julia = "1.10"
