name = "SequenceLogos"
uuid = "7a3f67ce-6eeb-4904-9da4-2cbd106a5944"
authors = "Jorge Fernandez-de-Cossio-Diaz <j.cossio.diaz@gmail.com>"
version = "0.2.0"

[deps]
PyPlot = "d330b81b-6aea-500a-939a-2ce795aea3ee"
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"

[compat]
julia = "1.6"
PyPlot = "2.9"
Colors = "0.12"
